# Generated by Django 5.2.5 on 2025-08-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('cathedra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directions', to='UniverEasy.cathedra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cathedras', to='UniverEasy.faculty'),
        ),
        migrations.CreateModel(
            name='FileWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='UniverEasy.direction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['slug'], name='UniverEasy__slug_c94314_idx')],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='univer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='UniverEasy.univer'),
        ),
        migrations.AddIndex(
            model_name='direction',
            index=models.Index(fields=['slug'], name='UniverEasy__slug_e06330_idx'),
        ),
        migrations.AddIndex(
            model_name='cathedra',
            index=models.Index(fields=['slug'], name='UniverEasy__slug_30d1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='filework',
            index=models.Index(fields=['slug'], name='UniverEasy__slug_c436bb_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['slug'], name='UniverEasy__slug_dbcd94_idx'),
        ),
    ]
