# Generated by Django 5.2.5 on 2025-08-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'бакалавр'), ('master', 'магистратура')], null=True),
        ),
    ]
