# Generated by Django 5.2.5 on 2025-08-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0002_direction_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='cathedra',
        ),
        migrations.RemoveField(
            model_name='filework',
            name='direction',
        ),
        migrations.AddField(
            model_name='filework',
            name='course',
            field=models.IntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='filework',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'бакалавр'), ('master', 'магистратура')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='filework',
            name='discipline',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filework',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='UniverEasy.faculty'),
        ),
        migrations.DeleteModel(
            name='Cathedra',
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
