# Generated by Django 5.2.5 on 2025-08-11 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0003_remove_direction_cathedra_remove_filework_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filework',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='filework',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filework',
            name='course',
            field=models.IntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filework',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'бакалавр'), ('master', 'магистратура'), ('specialty', 'специалитет')], default=None, null=True),
        ),
    ]
