# Generated by Django 5.2.5 on 2025-08-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0004_filework_file_filework_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filework',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
