# Generated by Django 5.2.5 on 2025-08-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0005_alter_filework_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filework',
            name='UniverEasy__slug_c436bb_idx',
        ),
        migrations.RenameField(
            model_name='filework',
            old_name='name',
            new_name='theme',
        ),
        migrations.RemoveField(
            model_name='filework',
            name='slug',
        ),
        migrations.AlterField(
            model_name='filework',
            name='course',
            field=models.IntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='filework',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'бакалавр'), ('master', 'магистратура'), ('specialty', 'специалитет')], default='bachelor', null=True),
        ),
    ]
