# Generated by Django 5.2.5 on 2025-08-11 20:48

import UniverEasy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0006_remove_filework_univereasy__slug_c436bb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filework',
            name='file',
            field=models.FileField(null=True, upload_to=UniverEasy.models.filepath),
        ),
    ]
