# Generated by Django 5.2.5 on 2025-08-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0007_alter_filework_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filework',
            name='edu_form',
            field=models.CharField(choices=[('distant', 'заочная'), ('full-time', 'очная')], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filework',
            name='course',
            field=models.IntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filework',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'бакалавр'), ('master', 'магистратура'), ('specialty', 'специалитет')], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filework',
            name='discipline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
