# Generated by Django 5.2.5 on 2025-08-14 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0008_filework_edu_form_alter_filework_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filework',
            name='variant',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
