# Generated by Django 5.2.5 on 2025-08-14 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0009_filework_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filework',
            name='variant',
            field=models.IntegerField(blank=True, default='', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
