# Generated by Django 5.2.5 on 2025-08-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniverEasy', '0010_alter_filework_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filework',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'бакалавр'), ('master', 'магистратура'), ('specialty', 'специалитет'), ('mid_prof_edu', 'среднее профессиональное образование')]),
        ),
    ]
